"""
app.py — The Wizard MLB Picks Dashboard
Streamlit frontend for the daily model pipeline.
"""
import streamlit as st
from supabase import create_client
import pandas as pd
from datetime import date, timedelta

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="The Wizard — MLB Picks",
    page_icon="🧙",
    layout="wide",
)

# ── Supabase connection ───────────────────────────────────────────────────────
@st.cache_resource
def get_supabase():
    return create_client(
        st.secrets["SUPABASE_URL"],
        st.secrets["SUPABASE_KEY"],
    )

supabase = get_supabase()

# ── Helpers ───────────────────────────────────────────────────────────────────
VERDICT_ORDER = {
    "✅ STRONG KEEP": 0,
    "🟡 KEEP":        1,
    "🟠 MARGINAL":    2,
    "❌ FAIL":        3,
}

def verdict_rank(v: str) -> int:
    for k, rank in VERDICT_ORDER.items():
        if k in str(v):
            return rank
    return 99

def color_verdict(v: str) -> str:
    if "STRONG KEEP" in str(v):
        return "background-color: #1a4731; color: #4ade80"
    if "KEEP" in str(v):
        return "background-color: #1c3a1c; color: #86efac"
    if "MARGINAL" in str(v):
        return "background-color: #3a2c0a; color: #fcd34d"
    if "FAIL" in str(v):
        return "background-color: #3a1515; color: #f87171"
    return ""

def color_result(v: str) -> str:
    if str(v) == "WIN":
        return "color: #4ade80; font-weight: bold"
    if str(v) == "LOSS":
        return "color: #f87171; font-weight: bold"
    if str(v) == "PUSH":
        return "color: #94a3b8; font-weight: bold"
    return ""

@st.cache_data(ttl=300)
def load_picks(run_date: str) -> pd.DataFrame:
    resp = supabase.table("wizard_picks").select("*").eq("game_date", run_date).execute()
    if not resp.data:
        return pd.DataFrame()
    df = pd.DataFrame([row["data"] for row in resp.data])
    df["_mfull_rank"] = df["MFull_verdict"].apply(verdict_rank)
    df["_mf5i_rank"]  = df["MF5i_verdict"].apply(verdict_rank)
    df = df.sort_values(["_mfull_rank", "_mf5i_rank"]).drop(columns=["_mfull_rank", "_mf5i_rank"])
    return df

@st.cache_data(ttl=300)
def load_tracker() -> pd.DataFrame:
    try:
        resp = supabase.table("bet_tracker").select("*").order("date", desc=True).execute()
        if not resp.data:
            return pd.DataFrame()
        return pd.DataFrame(resp.data)
    except Exception:
        return pd.DataFrame()

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🧙 The Wizard — MLB Model")
st.caption("Daily picks generated by the multi-model pipeline. Refresh after 10 AM ET for today's slate.")

st.divider()

# ── Date selector ─────────────────────────────────────────────────────────────
today = date.today()
selected_date = st.date_input(
    "Select date",
    value=today,
    min_value=date(2026, 4, 1),
    max_value=today,
)
run_date_str = selected_date.isoformat()

# ── Load picks ────────────────────────────────────────────────────────────────
df = load_picks(run_date_str)

if df.empty:
    st.warning(f"No picks found for {selected_date.strftime('%B %d, %Y')}. Pipeline may not have run yet.")
    st.stop()

# ── Summary stats bar ─────────────────────────────────────────────────────────
total_games = len(df)
strong_keeps = df["MFull_verdict"].str.contains("STRONG KEEP", na=False).sum()
keeps        = df["MFull_verdict"].str.contains("🟡 KEEP", na=False).sum()
mf5i_strong  = df["MF5i_verdict"].str.contains("STRONG KEEP", na=False).sum()

col1, col2, col3, col4 = st.columns(4)
col1.metric("Games Today",          total_games)
col2.metric("MFull Strong Keeps",   strong_keeps)
col3.metric("MFull Keeps",          keeps)
col4.metric("MF5i Strong Keeps",    mf5i_strong)

st.divider()

# ── Model tabs ────────────────────────────────────────────────────────────────
tab_full, tab_5i, tab_3i, tab_1i, tab_tracker = st.tabs([
    "MFull", "MF5i", "MF3i", "MF1i", "Bet Tracker"
])

# ── MFull tab ─────────────────────────────────────────────────────────────────
with tab_full:
    st.subheader("MFull — Full Season Model")
    cols = ["matchup", "home_sp", "away_sp", "MFull_lean", "MFull_prob",
            "MFull_verdict", "MFull_proj_total", "MFull_result"]
    available = [c for c in cols if c in df.columns]
    view = df[available].copy()
    view.columns = [c.replace("MFull_", "") for c in available]

    def style_full(row):
        styles = [""] * len(row)
        if "verdict" in row.index:
            idx = row.index.get_loc("verdict")
            styles[idx] = color_verdict(row["verdict"])
        if "result" in row.index:
            idx = row.index.get_loc("result")
            styles[idx] = color_result(row["result"])
        return styles

    st.dataframe(
        view.style.apply(style_full, axis=1),
        use_container_width=True,
        hide_index=True,
    )

# ── MF5i tab ──────────────────────────────────────────────────────────────────
with tab_5i:
    st.subheader("MF5i — First 5 Innings Model")
    cols = ["matchup", "home_sp", "away_sp", "MF5i_lean", "MF5i_prob",
            "MF5i_verdict", "MF5_cf", "MF5i_result"]
    available = [c for c in cols if c in df.columns]
    view = df[available].copy()
    view.columns = [c.replace("MF5i_", "").replace("MF5_", "cf_") for c in available]

    def style_5i(row):
        styles = [""] * len(row)
        if "verdict" in row.index:
            idx = row.index.get_loc("verdict")
            styles[idx] = color_verdict(row["verdict"])
        if "result" in row.index:
            idx = row.index.get_loc("result")
            styles[idx] = color_result(row["result"])
        return styles

    st.dataframe(
        view.style.apply(style_5i, axis=1),
        use_container_width=True,
        hide_index=True,
    )

# ── MF3i tab ──────────────────────────────────────────────────────────────────
with tab_3i:
    st.subheader("MF3i — First 3 Innings Model")
    cols = ["matchup", "home_sp", "away_sp", "MF3i_lean", "MF3i_prob",
            "MF3i_verdict", "MG3_proj", "MG3_cf", "M3_props", "MF3i_result"]
    available = [c for c in cols if c in df.columns]
    view = df[available].copy()

    def style_3i(row):
        styles = [""] * len(row)
        if "MF3i_verdict" in row.index:
            idx = row.index.get_loc("MF3i_verdict")
            styles[idx] = color_verdict(row["MF3i_verdict"])
        if "MF3i_result" in row.index:
            idx = row.index.get_loc("MF3i_result")
            styles[idx] = color_result(row["MF3i_result"])
        return styles

    st.dataframe(
        view.style.apply(style_3i, axis=1),
        use_container_width=True,
        hide_index=True,
    )

# ── MF1i tab ──────────────────────────────────────────────────────────────────
with tab_1i:
    st.subheader("MF1i — First Inning Model")
    cols = ["matchup", "home_sp", "away_sp", "MF1i_lean", "MF1i_prob",
            "MF1i_verdict", "MF1_proj", "MF1i_result"]
    available = [c for c in cols if c in df.columns]
    view = df[available].copy()

    def style_1i(row):
        styles = [""] * len(row)
        if "MF1i_verdict" in row.index:
            idx = row.index.get_loc("MF1i_verdict")
            styles[idx] = color_verdict(row["MF1i_verdict"])
        if "MF1i_result" in row.index:
            idx = row.index.get_loc("MF1i_result")
            styles[idx] = color_result(row["MF1i_result"])
        return styles

    st.dataframe(
        view.style.apply(style_1i, axis=1),
        use_container_width=True,
        hide_index=True,
    )

# ── Bet Tracker tab ───────────────────────────────────────────────────────────
with tab_tracker:
    st.subheader("Bet Tracker — Season Log")
    tracker_df = load_tracker()

    if tracker_df.empty:
        st.info("No bets logged yet.")
    else:
        # Season summary
        if "result" in tracker_df.columns and "profit_loss" in tracker_df.columns:
            wins   = (tracker_df["result"] == "WIN").sum()
            losses = (tracker_df["result"] == "LOSS").sum()
            pushes = (tracker_df["result"] == "PUSH").sum()
            total_pl = pd.to_numeric(tracker_df["profit_loss"], errors="coerce").sum()
            total_bets = wins + losses + pushes
            win_pct = (wins / total_bets * 100) if total_bets > 0 else 0

            c1, c2, c3, c4, c5 = st.columns(5)
            c1.metric("Record", f"{wins}-{losses}-{pushes}")
            c2.metric("Win %", f"{win_pct:.1f}%")
            c3.metric("Total P&L (units)", f"{total_pl:+.2f}")
            c4.metric("Wins", wins)
            c5.metric("Losses", losses)
            st.divider()

        st.dataframe(tracker_df, use_container_width=True, hide_index=True)

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption(f"Last refreshed: {date.today().strftime('%B %d, %Y')} · Data auto-refreshes every 5 minutes")
